name: gosec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gosec:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: ./.github/actions/setup-go

    - run: go install github.com/securego/gosec/v2/cmd/gosec@9e6a9843d7a4a6e3e9a8539b02612c8a4aa3f889 # v2.27.1

    - run: gosec ./...
